/**
 * Integration Test Runner: Module 1 (Python) → Module 2 (TypeScript)
 * 
 * Demonstrates end-to-end flow:
 * 1. Load baseline metrics from JSON
 * 2. Load current metrics from JSON
 * 3. Run reasoning engine
 * 4. Output decision
 * 
 * No hardcoded metrics; all data from JSON contract.
 */

import path from 'path';
import { fileURLToPath } from 'url';

// Early dotenv load (before any runtime imports)
import dotenv from 'dotenv';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({
  path: path.resolve(__dirname, '../../.env'),
});

import type { MetricsSnapshot } from './types.ts';

// ============================================================================
// BOUNDARY: File I/O and Loader
// ============================================================================

async function main() {
  // Dynamically import runtime modules after dotenv
  const [
    { loadMetricsSnapshot, loadMetricsSnapshotPair },
    { reason },
    { buildHypothesisPrompt },
  ] = await Promise.all([
    import('./metricsLoader.ts'),
    import('./index.ts'),
    import('./hypothesisGenerator.ts'),
  ]);

  console.log('\n========================================');
  console.log('  Integration Test: Module 1 ↔ Module 2');
  console.log('========================================\n');

  // Paths to metrics files (these would be generated by Module 1 / Python)
  const projectRoot = path.resolve(__dirname, '../../..');
  const baselineMetricsPath = path.join(projectRoot, 'agent-insight-engine/module1/output/baseline_metrics.json');
  const currentMetricsPath = path.join(projectRoot, 'agent-insight-engine/module1/output/current_metrics.json');

  console.log(`📂 Loading baseline metrics from: ${baselineMetricsPath}`);
  console.log(`📂 Loading current metrics from: ${currentMetricsPath}\n`);

  let baselineMetrics: MetricsSnapshot;
  let currentMetrics: MetricsSnapshot;

  try {
    // Load metrics from JSON (at boundary, with validation)
    [baselineMetrics, currentMetrics] = await loadMetricsSnapshotPair(
      baselineMetricsPath,
      currentMetricsPath
    );

    console.log('✅ Metrics loaded and validated against JSON contract\n');

    console.log('📊 Baseline Summary:');
    console.log(`   Success Rate: ${(baselineMetrics.successRate * 100).toFixed(2)}%`);
    console.log(`   Total Txns: ${baselineMetrics.totalTransactions}`);
    console.log(`   P95 Latency: ${baselineMetrics.latency.p95}ms\n`);

    console.log('📊 Current Summary:');
    console.log(`   Success Rate: ${(currentMetrics.successRate * 100).toFixed(2)}%`);
    console.log(`   Total Txns: ${currentMetrics.totalTransactions}`);
    console.log(`   P95 Latency: ${currentMetrics.latency.p95}ms\n`);

    // ========================================================================
    // CORE: Run Reasoning Engine (now with LLM required)
    // ========================================================================

    console.log('🧠 Running reasoning engine (LLM enabled)...\n');

    const result = await reason({
      currentMetrics,
      baselineMetrics,
      pastOutcomes: [],
      config: undefined, // Use default config
    });

    // ========================================================================
    // OUTPUT: Display Results
    // ========================================================================

    console.log('🔍 Anomalies Detected:');
    if (result.anomalies.length === 0) {
      console.log('   (none)');
    } else {
      result.anomalies.forEach((a, i) => {
        console.log(`   ${i + 1}. ${a.type} (${a.severity})`);
        console.log(`      Deviation: ${(a.deviation * 100).toFixed(1)}%`);
      });
    }
    console.log();

    console.log('🎯 Patterns Recognized:');
    if (result.patterns.length === 0) {
      console.log('   (none)');
    } else {
      result.patterns.forEach((p, i) => {
        console.log(`   ${i + 1}. ${p.type} (confidence: ${(p.confidence * 100).toFixed(0)}%)`);
      });
    }
    console.log();

    console.log('💡 Hypotheses Generated:');
    result.hypotheses.forEach((h, i) => {
      console.log(`   ${i + 1}. Pattern: ${h.pattern}`);
      console.log(`      Primary: ${h.primaryExplanation}`);
      console.log(`      Confidence: ${(h.confidence * 100).toFixed(0)}%\n`);
    });

    console.log('🚀 Decision:');
    console.log(`   Action: ${result.decision.selectedAction.type}`);
    console.log(`   Category: ${result.decision.selectedAction.category}`);
    console.log(`   Description: ${result.decision.selectedAction.description}`);
    console.log(`   Requires Approval: ${result.decision.requiresHumanApproval}`);
    console.log(`   Confidence: ${(result.decision.confidenceInDecision * 100).toFixed(0)}%`);
    console.log();

    console.log('⏱️  Processing Time:', result.processingTime, 'ms');
    console.log();

    // ========================================================================
    // FULL RESULT (JSON)
    // ========================================================================

    console.log('📋 Full Result (JSON):');
    console.log(JSON.stringify(result, null, 2));
    console.log();

    console.log('✅ Integration test completed successfully!');
  } catch (err) {
    console.error('❌ Error:', (err as Error).message);
    console.error((err as Error).stack);
    process.exit(1);
  }
}

main();
